default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres

development:
  <<: *default
  database: aglipay_swe_jwt_development

test:
  <<: *default
  database: aglipay_swe_jwt_test
